import type { MetadataRoute } from "next";
import { BRAND_COLORS, SITE_NAME, SITE_SHORT_NAME, absoluteUrl } from "@/lib/site";

/**
 * PWA / Web App Manifest
 *
 * Serves `/manifest.webmanifest` and is referenced by the `manifest`
 * key in the root `metadata` export. All icons referenced here are
 * generated by the file-based metadata API (`app/icon.tsx`,
 * `app/apple-icon.tsx`) so they stay in sync with the brand.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE_NAME} POS — Caisse moderne pour lounge bar`,
    short_name: SITE_SHORT_NAME,
    description:
      "JOAC POS — application de caisse moderne pour lounge bar : ventes, commandes, stock, caissiers, rapports et facturation FC / USD en temps réel.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    display_override: ["window-controls-overlay", "standalone", "browser"],
    orientation: "portrait-primary",
    background_color: BRAND_COLORS.backgroundLight,
    theme_color: BRAND_COLORS.primary,
    lang: "fr-CD",
    dir: "ltr",
    categories: [
      "business",
      "finance",
      "productivity",
      "shopping",
      "food",
    ],
    id: "/",
    prefer_related_applications: false,
    launch_handler: {
      client_mode: ["auto"],
    },
    protocol_handlers: [
      {
        protocol: "web+joac",
        url: absoluteUrl("/open?path=%s"),
      },
    ],
    icons: [
      {
        src: absoluteUrl("/logo_ass_N-clair.png"),
        sizes: "any",
        type: "image/png",
        purpose: "any",
      },
      {
        src: absoluteUrl("/logo_ass_N-clair.png"),
        sizes: "any",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    screenshots: [
      {
        src: absoluteUrl("/screenshot-desktop.png"),
        sizes: "1280x720",
        type: "image/png",
        form_factor: "wide",
        label: "Vue bureau du POS JOAC",
      },
      {
        src: absoluteUrl("/screenshot-mobile.png"),
        sizes: "390x844",
        type: "image/png",
        form_factor: "narrow",
        label: "Vue mobile du POS JOAC",
      },
    ],
    shortcuts: [
      {
        name: "Caisse",
        short_name: "Caisse",
        description: "Ouvrir directement la caisse (POS)",
        url: "/",
        icons: [
          {
            src: absoluteUrl("/icon-96x96.png"),
            sizes: "96x96",
            type: "image/png",
          },
        ],
      },
      {
        name: "Tableau de bord",
        short_name: "Dashboard",
        description: "Voir le tableau de bord & les analytics",
        url: "/dashboard",
        icons: [
          {
            src: absoluteUrl("/icon-96x96.png"),
            sizes: "96x96",
            type: "image/png",
          },
        ],
      },
      {
        name: "Stock",
        short_name: "Stock",
        description: "Gérer le stock et les produits",
        url: "/stock",
        icons: [
          {
            src: absoluteUrl("/icon-96x96.png"),
            sizes: "96x96",
            type: "image/png",
          },
        ],
      },
      {
        name: "Rapports",
        short_name: "Rapports",
        description: "Consulter les rapports de vente",
        url: "/reports",
        icons: [
          {
            src: absoluteUrl("/icon-96x96.png"),
            sizes: "96x96",
            type: "image/png",
          },
        ],
      },
    ],
    share_target: {
      action: "/share",
      method: "POST",
      enctype: "multipart/form-data",
      params: {
        title: "title",
        text: "text",
        url: "url",
        files: [
          {
            name: "files",
            accept: ["image/*", "application/pdf"],
          },
        ],
      },
    },
    file_handlers: [
      {
        action: "/open",
        accept: {
          "application/pdf": [".pdf"],
          "text/csv": [".csv"],
          "image/*": [".png", ".jpg", ".jpeg", ".webp"],
        },
      },
    ],
    related_applications: [],
  };
}
