import type { Category, Drink } from "./types"

export const categories: Category[] = [
  { id: "all", label: "All" },
  { id: "water", label: "Water" },
  { id: "energy", label: "Energy" },
  { id: "other", label: "Other" },
  { id: "whiskies", label: "Whiskies" },
  { id: "vins", label: "Vins" },
  { id: "champagnes", label: "Champagnes" },
  { id: "vodka", label: "Vodka" },
  { id: "cognacs", label: "Cognacs" },
  { id: "tequilas", label: "Tequilas" },
  { id: "liqueurs", label: "Liqueurs" },
  { id: "bieres", label: "Bières" },
  { id: "soft", label: "Soft" },
]
export const drinks: Drink[] = [
  { id: "sir-edwards", name: "Sir Edward's", description: "", price: 30, category: "whiskies", image: "/drinks/Sir Edward's.jpeg", stock: 100, popularity: 1 },
  { id: "grants-75cl", name: "Grant's 75 cl", description: "", price: 35, category: "whiskies", image: "/drinks/Grant's.jpeg", stock: 100, popularity: 1 },
  { id: "mouton-cadet", name: "Mouton Cadet", description: "", price: 35, category: "vins", image: "/drinks/Mouton Cadet.jpeg", stock: 0, popularity: 1 },
  { id: "red-label", name: "Red Label", description: "", price: 40, category: "whiskies", image: "/drinks/red Label.jpeg", stock: 100, popularity: 1 },
  { id: "black-label", name: "Black Label", description: "", price: 60, category: "whiskies", image: "/drinks/Black Label.jpeg", stock: 100, popularity: 1 },
  { id: "double-black", name: "Double Black", description: "", price: 80, category: "whiskies", image: "/drinks/double Label.jpeg", stock: 100, popularity: 1 },
  { id: "gold-label", name: "Gold Label", description: "", price: 90, category: "whiskies", image: "/drinks/Gold Label.jpeg", stock: 100, popularity: 1 },
  { id: "absolut-vodka-75cl", name: "Absolut Vodka 75 cl", description: "", price: 40, category: "vodka", image: "/drinks/Absolut Vodka 75 cl.jpeg", stock: 100, popularity: 1 },
  { id: "baileys", name: "Baileys", description: "", price: 40, category: "liqueurs", image: "/drinks/Baileys.jpeg", stock: 100, popularity: 1 },
  { id: "cointreau", name: "Cointreau", description: "", price: 70, category: "liqueurs", image: "/drinks/Cointreau.jpeg", stock: 100, popularity: 1 },
  { id: "jameson", name: "Jameson", description: "", price: 50, category: "whiskies", image: "/drinks/Jameson.jpeg", stock: 100, popularity: 1 },
  { id: "jagermeister-50cl", name: "Jägermeister 50 cl", description: "", price: 50, category: "liqueurs", image: "/drinks/Jägermeister.jpeg", stock: 100, popularity: 1 },
  { id: "jagermeister-1l", name: "Jägermeister 1 L", description: "", price: 80, category: "liqueurs", image: "/drinks/Jägermeister.jpeg", stock: 100, popularity: 1 },
  { id: "jack-daniels-70cl", name: "Jack Daniel's 70 cl", description: "", price: 70, category: "whiskies", image: "/drinks/Jack Daniel's.jpeg", stock: 100, popularity: 1 },
  { id: "jack-daniels-honey-70cl", name: "Jack Daniel's Honey 70 cl", description: "", price: 75, category: "whiskies", image: "/drinks/Jack Daniel's Honey.jpeg", stock: 100, popularity: 1 },
  { id: "chivas-12-75cl", name: "Chivas 12 ans 75 cl", description: "", price: 75, category: "whiskies", image: "/drinks/Chivas.jpeg", stock: 100, popularity: 1 },
  { id: "hennessy-vs", name: "Hennessy VS", description: "", price: 80, category: "cognacs", image: "/drinks/Hennessy vs.jpeg", stock: 100, popularity: 1 },
  { id: "hennessy-vsop", name: "Hennessy VSOP", description: "", price: 150, category: "cognacs", image: "/drinks/Hennessy VSOP.jpeg", stock: 100, popularity: 1 },
  { id: "martell-blue-swift", name: "Martell Blue Swift", description: "", price: 100, category: "cognacs", image: "/drinks/Martell Blue Swift.jpeg", stock: 100, popularity: 1 },
  { id: "camino-real-blanco-75cl", name: "Camino Real Blanco 75 cl", description: "", price: 40, category: "tequilas", image: "/drinks/Camino Real Blanco.jpeg", stock: 100, popularity: 1 },
  { id: "olmeca", name: "Olmeca", description: "", price: 50, category: "tequilas", image: "/drinks/olmeca.jpeg", stock: 100, popularity: 1 },
  { id: "don-julio-blanco", name: "Don Julio Blanco", description: "", price: 100, category: "tequilas", image: "/drinks/Don Julio Blanco.jpeg", stock: 100, popularity: 1 },
  { id: "baron-darignac", name: "Baron d'Arignac", description: "", price: 50, category: "vins", image: "/drinks/Baron d'Arignac.jpeg", stock: 100, popularity: 1 },
  { id: "jp-chenet", name: "JP. Chenet", description: "", price: 50, category: "vins", image: "/drinks/JP. Chenet.jpeg", stock: 100, popularity: 1 },
  { id: "moet-brut", name: "Moët Brut", description: "", price: 100, category: "champagnes", image: "/drinks/moet brut.jpeg", stock: 100, popularity: 1 },
  { id: "moet-ice-imperial", name: "Moët Ice Impérial", description: "", price: 120, category: "champagnes", image: "/drinks/moet ice.jpeg", stock: 100, popularity: 1 },
  { id: "moet-nectar-imperial", name: "Moët Nectar Impérial", description: "", price: 150, category: "champagnes", image: "/drinks/moét nectar imperial.jpeg", stock: 100, popularity: 1 },
  { id: "veuve-clicquot", name: "Veuve Clicquot", description: "", price: 180, category: "champagnes", image: "/drinks/moet brut.jpeg", stock: 100, popularity: 1 },
  { id: "ruinart-blanc-de-blancs", name: "Ruinart Blanc de Blancs", description: "", price: 250, category: "champagnes", image: "/drinks/ruinart.jpeg", stock: 100, popularity: 1 },
  { id: "armand-de-brignac", name: "Armand de Brignac", description: "", price: 600, category: "champagnes", image: "/drinks/moet brut.jpeg", stock: 100, popularity: 1 },
  { id: "bavaria", name: "Bavaria", description: "", price: 10000, category: "bieres", image: "/drinks/bavaria.jpeg", stock: 100, popularity: 1 },
  { id: "savana", name: "Savana", description: "", price: 10000, category: "bieres", image: "/drinks/savana.jpeg", stock: 100, popularity: 1 },
  { id: "leffe", name: "Leffe", description: "", price: 14000, category: "bieres", image: "/drinks/leffe.jpeg", stock: 100, popularity: 1 },
  { id: "xxl", name: "XXL", description: "", price: 4500, category: "energy", image: "/drinks/energy.png", stock: 100, popularity: 1 },
  { id: "energy-malt", name: "Energy Malt", description: "", price: 4500, category: "energy", image: "/drinks/energy.png", stock: 100, popularity: 1 },
  { id: "red-bull", name: "Red Bull", description: "", price: 10000, category: "energy", image: "/drinks/red bull.jpeg", stock: 100, popularity: 1 },
  { id: "coca-cola", name: "Coca Cola", description: "", price: 4500, category: "soft", image: "/drinks/coca.jpeg", stock: 100, popularity: 1 },
  { id: "fanta", name: "Fanta", description: "", price: 4500, category: "soft", image: "/drinks/fanta.jpeg", stock: 100, popularity: 1 },
  { id: "maltina", name: "Maltina", description: "", price: 4500, category: "soft", image: "/drinks/maltina.jpeg", stock: 100, popularity: 1 },
  { id: "vitalo", name: "Vitalo", description: "", price: 4500, category: "soft", image: "/drinks/lemonade.png", stock: 100, popularity: 1 },
  { id: "tonic", name: "Tonic", description: "", price: 4500, category: "soft", image: "/drinks/tonic.jpeg", stock: 100, popularity: 1 },
  { id: "castel", name: "Castel", description: "", price: 7000, category: "bieres", image: "/drinks/castel.jpeg", stock: 100, popularity: 1 },
  { id: "beaufort-gd", name: "Beaufort GD", description: "", price: 7000, category: "bieres", image: "/drinks/beaufort.jpeg", stock: 100, popularity: 1 },
  { id: "tembo", name: "Tembo", description: "", price: 10000, category: "bieres", image: "/drinks/bavaria.jpeg", stock: 100, popularity: 1 },
  { id: "nkoyi", name: "Nkoyi", description: "", price: 7000, category: "bieres", image: "/drinks/bavaria.jpeg", stock: 100, popularity: 1 },
  { id: "primus", name: "Primus", description: "", price: 7000, category: "bieres", image: "/drinks/Primus.jpeg", stock: 100, popularity: 1 },
  { id: "turbo", name: "Turbo", description: "", price: 6000, category: "bieres", image: "/drinks/bavaria.jpeg", stock: 100, popularity: 1 },
  { id: "mutzing", name: "Mutzing", description: "", price: 6000, category: "bieres", image: "/drinks/bavaria.jpeg", stock: 100, popularity: 1 },
  { id: "heineken", name: "Heineken", description: "", price: 6000, category: "bieres", image: "/drinks/Heineken.jpeg", stock: 100, popularity: 1 },
  { id: "legend-gd", name: "Legend GD", description: "", price: 7000, category: "bieres", image: "/drinks/bavaria.jpeg", stock: 100, popularity: 1 },
  { id: "tiger", name: "Tiger", description: "", price: 6000, category: "bieres", image: "/drinks/tiger.jpeg", stock: 100, popularity: 1 },
  { id: "water", name: "Water", description: "", price: 1000, category: "water", image: "/drinks/water.png", stock: 500, popularity: 1 },
]

export const presetThemes = [
  {
    name: "Royal Gold",
    primaryColor: "#D4AF37",
    secondaryColor: "#FFF8E1",
  },
  {
    name: "Emerald",
    primaryColor: "#10B981",
    secondaryColor: "#D1FAE5",
  },
  {
    name: "Ruby Lounge",
    primaryColor: "#B91C1C",
    secondaryColor: "#FEE2E2",
  },
  {
    name: "Champagne",
    primaryColor: "#EAB308",
    secondaryColor: "#FEF9C3",
  },
  {
    name: "Royal Purple",
    primaryColor: "#7C3AED",
    secondaryColor: "#EDE9FE",
  },
  {
    name: "Sapphire",
    primaryColor: "#2563EB",
    secondaryColor: "#DBEAFE",
  },
  {
    name: "Copper",
    primaryColor: "#B45309",
    secondaryColor: "#FEF3C7",
  },
  {
    name: "Rose Gold",
    primaryColor: "#BE5672",
    secondaryColor: "#FCE7F3",
  },
  {
    name: "Obsidian",
    primaryColor: "#111827",
    secondaryColor: "#F3F4F6",
  },

]

export const salesTrend = [
  { day: "Mon", sales: 420 },
  { day: "Tue", sales: 510 },
  { day: "Wed", sales: 480 },
  { day: "Thu", sales: 620 },
  { day: "Fri", sales: 790 },
  { day: "Sat", sales: 910 },
  { day: "Sun", sales: 680 },
]

export const topSellers = [
  { name: "double-black", sold: 142 },
  { name: "Cola Classic", sold: 118 },
  { name: "Caffe Latte", sold: 96 },
  { name: "Iced Americano", sold: 71 },
]
